<?php

/**
 * BaseOdkazy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $poradi
 * @property string $name
 * @property string $link
 * @property boolean $publikovat
 * 
 * @method integer getId()         Returns the current record's "id" value
 * @method integer getPoradi()     Returns the current record's "poradi" value
 * @method string  getName()       Returns the current record's "name" value
 * @method string  getLink()       Returns the current record's "link" value
 * @method boolean getPublikovat() Returns the current record's "publikovat" value
 * @method Odkazy  setId()         Sets the current record's "id" value
 * @method Odkazy  setPoradi()     Sets the current record's "poradi" value
 * @method Odkazy  setName()       Sets the current record's "name" value
 * @method Odkazy  setLink()       Sets the current record's "link" value
 * @method Odkazy  setPublikovat() Sets the current record's "publikovat" value
 * 
 * @package    dunaverde
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseOdkazy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('odkazy');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('poradi', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'unique' => true,
             'length' => 50,
             ));
        $this->hasColumn('link', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('publikovat', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}